title: RepoSense Report
repos:
  - repo: https://github.com/RepoSense/reposense.git
    groups:
      - group-name: code
        globs:
          - "**.java"
    branches:
      - branch: master
        blurb: "Reposense is a code contribution analysis tool which I contributed."
        since: 27/7/2025 12:00
        authors:
          - author-git-host-id: lyuanww
            author-display-name: Li Yuan
            author-emails:
              - user@gmail.com
              - e0123456@u.nus.edu
  - repo: https://github.com/lyuanww/ip.git
    groups:
      - group-name: code
        globs:
          - "**.java"
    branches:
      - branch: master
        blurb: "A task manager chat bot implemented in Java."
        since: 01/01/2025 12:00
        authors:
          - author-git-host-id: lyuanww
            author-display-name: Li Yuan
            author-emails:
              - user@gmail.com
              - e0123456@u.nus.edu
      - branch: add-gradle-support
        blurb: "happy"
        since: 01/01/2025 12:00
        authors:
          - author-git-host-id: lyuanww
            author-display-name: Li Yuan
            author-emails:
              - user@gmail.com
              - e0123456@u.nus.edu
      