title: My Code Portfolio
repos:
  - repo: https://github.com/AY2425S2-CS2103T-W09-2/tp.git
    groups:
      - group-name: code
        globs:
          - "**.java"
    branches:
      - blurb: "W09-2 TP"
        since: 20-2-2025 13:20:10
        until: 15-03-2025
        authors:
          - author-git-host-id: aekyr
          - author-git-host-id: Noob-No-1
          - author-git-host-id: salads-source
          - author-git-host-id: shelialia
          - author-git-host-id: juniper285
  - repo: https://github.com/AY2425S2-CS2103T-W09-1/tp.git
    groups:
      - group-name: code
        globs:
          - "**.java"
    branches:
      - blurb: "W09-1 TP Goated"
        since: 16/03/2025 13:02
        until: 10/04/2025 21:09